version: '2.1'
services:

  pinpoint-hbase:
    container_name: pinpoint-hbase
    hostname: pinpoint-hbase
    image: dawidmalina/pinpoint-hbase:1.8.0-RC1
    restart: always
    expose:
      - "2181"
      - "16010"
    ports:
      - "2181:2181"
      - "16010:16010"
#    volumes:
#      - /path/to/hbase/data:/home/pinpoint/hbase:rw
#      - /path/to/zookeeper/data:/home/pinpoint/zookeeper:rw

  pinpoint-collector:
    container_name: pinpoint-collector
    hostname: collector
    image: dawidmalina/pinpoint-collector:1.8.0-RC1
    depends_on:
      - pinpoint-hbase
    restart: always
    expose:
      - "9994"
      - "9995"
      - "9996"
    ports:
      - "9994:9994"
      - "9995:9995/tcp"
      - "9996:9996/tcp"
      - "9995:9995/udp"
      - "9996:9996/udp"
    environment:
      HBASE_HOST: pinpoint-hbase
      HBASE_PORT: 2181
      COLLECTOR_TCP_PORT: 9994
      COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
      COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
      CLUSTER_ENABLE: 'true'
      CLUSTER_ZOOKEEPER_ADDRESS: pinpoint-hbase
      FLINK_CLUSTER_ENABLE: 'true'
      FLINK_CLUSTER_ZOOKEEPER_ADDRESS: pinpoint-hbase
      DISABLE_DEBUG: 'true'

  pinpoint-web:
    container_name: pinpoint-web
    hostname: web
    image: dawidmalina/pinpoint-web:1.8.0-RC1
    depends_on:
      - pinpoint-hbase
    restart: always
    expose:
      - "8080"
      - "9997"
    ports:
      - "9997:9997"
      - "8080:8080"
    environment:
      HBASE_HOST: pinpoint-hbase
      HBASE_PORT: 2181
      CLUSTER_ENABLE: 'true'
      CLUSTER_ZOOKEEPER_ADDRESS: pinpoint-hbase
      CLUSTER_WEB_TCP_PORT: 9997
      ADMIN_PASSWORD: admin123
      DISABLE_ANALYTICS: 'true'
      ENABLE_APPLICATION_INSPECTOR: 'true'
      DISABLE_DEBUG: 'true'

  # only example
#  pinpoint-agent:
#    image: dawidmalina/pinpoint-agent:1.8.0-RC1
#    net: "none"
#    restart: unless-stopped
#    volumes:
#      - /var/container_data/pinpoint-agent/log:/opt/app/pinpoint-agent/log:rw
#    environment:
#      COLLECTOR_IP: 192.168.99.100
#      COLLECTOR_TCP_PORT: 9994
#      COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
#      COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
#      PROFILER_SAMPLING_RATE: 1
#      DISABLE_DEBUG: 'true'
